# -*- coding: utf-8 -*-
"""My Affiliate Page

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rsWIg-kNic_I9mcJZHKLd04uv4WB8Zg
"""

import streamlit as st

# --- PAGE CONFIGURATION ---
# Set the page configuration.
# This must be the first Streamlit command used in your app.
st.set_page_config(
    page_title="My Top Products",  # The title of the page in the browser tab
    page_icon="🛍️",               # An emoji for the page icon
    layout="wide"                 # Use "wide" layout to use more screen space
)

# --- HEADER SECTION ---
# Add a title and a short introduction.
st.title("🛍️ My Favorite Products")
st.write("Here are some of the products I use and recommend. As an affiliate, I may earn from qualifying purchases.")

# --- PRODUCT 1 ---
st.markdown("---") # Adds a horizontal line

# Create two columns for layout: one for the image, one for the text
col1, col2 = st.columns([1, 2]) # Image column is 1/3, text column is 2/3

with col1:
    st.image(
        "https://via.placeholder.com/300x300.png?text=Product+Image", # Replace with your product image URL
        caption="My Favorite Gadget",
        use_column_width=True
    )

with col2:
    st.subheader("Awesome Product Name")
    st.write(
        """
        This is a little description of the product.
        I love it because it's easy to use, has a great battery life,
        and has helped me save a lot of time.
        """
    )
    # The affiliate link button
    st.link_button(
        "Buy Now on Amazon",                                 # Button text
        "https://www.amazon.com/s?k=your-affiliate-link-here" # Replace with your affiliate link
    )

# --- PRODUCT 2 ---
st.markdown("---") # Adds a horizontal line

col1, col2 = st.columns([1, 2])

with col1:
    st.image(
        "https://via.placeholder.com/300x300.png?text=Another+Product", # Replace with your product image URL
        caption="My Go-To Skincare",
        use_column_width=True
    )

with col2:
    st.subheader("Amazing Skincare Cream")
    st.write(
        """
        Another short description. This cream is fantastic for all
        skin types and is made with all-natural ingredients.
        A must-have in my daily routine.
        """
    )
    # The affiliate link button
    st.link_button(
        "Buy Now on Sephora",                                # Button text
        "https://www.sephora.com/s?k=your-affiliate-link-here" # Replace with your affiliate link
    )

# --- AFFILIATE DISCLOSURE ---
st.markdown("---")
st.caption("As an Amazon Associate (or other affiliate program), I earn from qualifying purchases. This page contains affiliate links.")